// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: learn.proto
// Protobuf C++ Version: 5.27.1

#include "learn.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr Manufactured::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        adress_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        line_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        year_{0},
        foreign_economics_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Manufactured::Manufactured(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct ManufacturedDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ManufacturedDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ManufacturedDefaultTypeInternal() {}
  union {
    Manufactured _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ManufacturedDefaultTypeInternal _Manufactured_default_instance_;
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_learn_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_learn_2eproto = nullptr;
const ::uint32_t
    TableStruct_learn_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::Manufactured, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::Manufactured, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::Manufactured, _impl_.year_),
        PROTOBUF_FIELD_OFFSET(::Manufactured, _impl_.adress_),
        PROTOBUF_FIELD_OFFSET(::Manufactured, _impl_.name_),
        PROTOBUF_FIELD_OFFSET(::Manufactured, _impl_.line_),
        PROTOBUF_FIELD_OFFSET(::Manufactured, _impl_.foreign_economics_),
        3,
        0,
        1,
        2,
        4,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 13, -1, sizeof(::Manufactured)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::_Manufactured_default_instance_._instance,
};
const char descriptor_table_protodef_learn_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\013learn.proto\"c\n\014Manufactured\022\014\n\004year\030\001 "
    "\002(\005\022\016\n\006adress\030\002 \002(\t\022\014\n\004name\030\003 \002(\t\022\014\n\004lin"
    "e\030\004 \001(\t\022\031\n\021foreign_economics\030\005 \001(\005"
};
static ::absl::once_flag descriptor_table_learn_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_learn_2eproto = {
    false,
    false,
    114,
    descriptor_table_protodef_learn_2eproto,
    "learn.proto",
    &descriptor_table_learn_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_learn_2eproto::offsets,
    file_level_enum_descriptors_learn_2eproto,
    file_level_service_descriptors_learn_2eproto,
};
// ===================================================================

class Manufactured::_Internal {
 public:
  using HasBits =
      decltype(std::declval<Manufactured>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Manufactured, _impl_._has_bits_);
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x0000000b) ^ 0x0000000b) != 0;
  }
};

Manufactured::Manufactured(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Manufactured)
}
inline PROTOBUF_NDEBUG_INLINE Manufactured::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::Manufactured& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        adress_(arena, from.adress_),
        name_(arena, from.name_),
        line_(arena, from.line_) {}

Manufactured::Manufactured(
    ::google::protobuf::Arena* arena,
    const Manufactured& from)
    : ::google::protobuf::Message(arena) {
  Manufactured* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, year_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, year_),
           offsetof(Impl_, foreign_economics_) -
               offsetof(Impl_, year_) +
               sizeof(Impl_::foreign_economics_));

  // @@protoc_insertion_point(copy_constructor:Manufactured)
}
inline PROTOBUF_NDEBUG_INLINE Manufactured::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        adress_(arena),
        name_(arena),
        line_(arena) {}

inline void Manufactured::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, year_),
           0,
           offsetof(Impl_, foreign_economics_) -
               offsetof(Impl_, year_) +
               sizeof(Impl_::foreign_economics_));
}
Manufactured::~Manufactured() {
  // @@protoc_insertion_point(destructor:Manufactured)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Manufactured::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.adress_.Destroy();
  _impl_.name_.Destroy();
  _impl_.line_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
Manufactured::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              Manufactured::IsInitializedImpl,
              PROTOBUF_FIELD_OFFSET(Manufactured, _impl_._cached_size_),
              false,
          },
          &Manufactured::MergeImpl,
          &Manufactured::kDescriptorMethods,
          &descriptor_table_learn_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 0, 35, 2> Manufactured::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Manufactured, _impl_._has_bits_),
    0, // no _extensions_
    5, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_Manufactured_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Manufactured>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // required int32 year = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Manufactured, _impl_.year_), 3>(),
     {8, 3, 0, PROTOBUF_FIELD_OFFSET(Manufactured, _impl_.year_)}},
    // required string adress = 2;
    {::_pbi::TcParser::FastSS1,
     {18, 0, 0, PROTOBUF_FIELD_OFFSET(Manufactured, _impl_.adress_)}},
    // required string name = 3;
    {::_pbi::TcParser::FastSS1,
     {26, 1, 0, PROTOBUF_FIELD_OFFSET(Manufactured, _impl_.name_)}},
    // optional string line = 4;
    {::_pbi::TcParser::FastSS1,
     {34, 2, 0, PROTOBUF_FIELD_OFFSET(Manufactured, _impl_.line_)}},
    // optional int32 foreign_economics = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Manufactured, _impl_.foreign_economics_), 4>(),
     {40, 4, 0, PROTOBUF_FIELD_OFFSET(Manufactured, _impl_.foreign_economics_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // required int32 year = 1;
    {PROTOBUF_FIELD_OFFSET(Manufactured, _impl_.year_), _Internal::kHasBitsOffset + 3, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // required string adress = 2;
    {PROTOBUF_FIELD_OFFSET(Manufactured, _impl_.adress_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
    // required string name = 3;
    {PROTOBUF_FIELD_OFFSET(Manufactured, _impl_.name_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
    // optional string line = 4;
    {PROTOBUF_FIELD_OFFSET(Manufactured, _impl_.line_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
    // optional int32 foreign_economics = 5;
    {PROTOBUF_FIELD_OFFSET(Manufactured, _impl_.foreign_economics_), _Internal::kHasBitsOffset + 4, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
    "\14\0\6\4\4\0\0\0"
    "Manufactured"
    "adress"
    "name"
    "line"
  }},
};

PROTOBUF_NOINLINE void Manufactured::Clear() {
// @@protoc_insertion_point(message_clear_start:Manufactured)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      _impl_.adress_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      _impl_.name_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000004u) {
      _impl_.line_.ClearNonDefaultToEmpty();
    }
  }
  if (cached_has_bits & 0x00000018u) {
    ::memset(&_impl_.year_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.foreign_economics_) -
        reinterpret_cast<char*>(&_impl_.year_)) + sizeof(_impl_.foreign_economics_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* Manufactured::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Manufactured)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // required int32 year = 1;
  if (cached_has_bits & 0x00000008u) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_year(), target);
  }

  // required string adress = 2;
  if (cached_has_bits & 0x00000001u) {
    const std::string& _s = this->_internal_adress();
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                "Manufactured.adress");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // required string name = 3;
  if (cached_has_bits & 0x00000002u) {
    const std::string& _s = this->_internal_name();
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                "Manufactured.name");
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  // optional string line = 4;
  if (cached_has_bits & 0x00000004u) {
    const std::string& _s = this->_internal_line();
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                "Manufactured.line");
    target = stream->WriteStringMaybeAliased(4, _s, target);
  }

  // optional int32 foreign_economics = 5;
  if (cached_has_bits & 0x00000010u) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<5>(
            stream, this->_internal_foreign_economics(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Manufactured)
  return target;
}

::size_t Manufactured::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Manufactured)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    // required string adress = 2;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this->_internal_adress());
    }

    // required string name = 3;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this->_internal_name());
    }

  }
  // optional string line = 4;
  if (cached_has_bits & 0x00000004u) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_line());
  }

  // required int32 year = 1;
  if (cached_has_bits & 0x00000008u) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_year());
  }

  // optional int32 foreign_economics = 5;
  if (cached_has_bits & 0x00000010u) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_foreign_economics());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void Manufactured::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Manufactured*>(&to_msg);
  auto& from = static_cast<const Manufactured&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Manufactured)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x0000001fu) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_adress(from._internal_adress());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_set_name(from._internal_name());
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_internal_set_line(from._internal_line());
    }
    if (cached_has_bits & 0x00000008u) {
      _this->_impl_.year_ = from._impl_.year_;
    }
    if (cached_has_bits & 0x00000010u) {
      _this->_impl_.foreign_economics_ = from._impl_.foreign_economics_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Manufactured::CopyFrom(const Manufactured& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Manufactured)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool Manufactured::IsInitializedImpl(
    const MessageLite& msg) {
  auto& this_ = static_cast<const Manufactured&>(msg);
  if (_Internal::MissingRequiredFields(this_._impl_._has_bits_)) {
    return false;
  }
  return true;
}

void Manufactured::InternalSwap(Manufactured* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.adress_, &other->_impl_.adress_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.line_, &other->_impl_.line_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Manufactured, _impl_.foreign_economics_)
      + sizeof(Manufactured::_impl_.foreign_economics_)
      - PROTOBUF_FIELD_OFFSET(Manufactured, _impl_.year_)>(
          reinterpret_cast<char*>(&_impl_.year_),
          reinterpret_cast<char*>(&other->_impl_.year_));
}

::google::protobuf::Metadata Manufactured::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_learn_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
